# Generated by Django 6.1 on 2026-09-09 09:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('short_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('applicable_trl_levels', models.CharField(blank=True, help_text="e.g. 'TRL-4,TRL-5,TRL-6' — from the KP-TRL master sheet", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TRLDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('milestone_1', models.CharField(blank=True, max_length=255)),
                ('milestone_2', models.CharField(blank=True, max_length=255)),
                ('milestone_3', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('innovator_name', models.CharField(blank=True, max_length=200)),
                ('affiliation_type', models.CharField(choices=[('individual', 'Individual'), ('institute', 'Institute/Company')], default='individual', max_length=30)),
                ('affiliation_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('medtech_type', models.CharField(choices=[('device', 'Medical Device'), ('ivd', 'Diagnostic'), ('Therapists', 'Therapists'), ('Vaccine', 'Vaccine'), ('assisttech', 'Assistive Technology')], max_length=10)),
                ('technology_name', models.CharField(max_length=255)),
                ('intended_use_statement', models.TextField(blank=True)),
                ('use_environment', models.CharField(blank=True, max_length=255)),
                ('target_population', models.TextField(blank=True)),
                ('area_of_application', models.TextField(blank=True)),
                ('risk_classification', models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D'), ('unknown', 'Not Known')], default='unknown', max_length=10)),
                ('device_category', models.CharField(blank=True, choices=[('predicate', 'Medical device/IVD having available predicate device'), ('investigational', 'Investigational Medical Device/IVD')], max_length=20)),
                ('innovation_stage', models.CharField(blank=True, choices=[('concept_dev', 'Under Concept Development'), ('concept_proved', 'Concept Proved with Prototype'), ('bench_testing', 'Bench Testing of Prototypes for Manufacturing'), ('clinical_testing', 'Clinical Testing for National Program'), ('clinical_investigation', 'Clinical Investigation/Performance Evaluation')], max_length=30)),
                ('support_type_requested', models.CharField(blank=True, max_length=255)),
                ('support_category', models.CharField(blank=True, choices=[('advisory', 'Advisory'), ('handholding', 'Handholding')], max_length=15)),
                ('test_license_received', models.BooleanField(blank=True, null=True)),
                ('query_text', models.TextField(blank=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('closed', 'Closed'), ('resolved', 'Resolved'), ('assigned_to_kp', 'Assigned to Knowledge Partner')], db_index=True, default='in_progress', max_length=20)),
                ('initial_trl_date', models.DateField(blank=True, null=True)),
                ('current_trl_date', models.DateField(blank=True, null=True)),
                ('final_status_notes', models.TextField(blank=True)),
                ('final_status_date', models.DateField(blank=True, null=True)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.applicant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_trl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.trldefinition')),
                ('final_trl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.trldefinition')),
                ('initial_trl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.trldefinition')),
            ],
            options={
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTRLStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=15)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trl_stages', to='core.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.trldefinition')),
            ],
            options={
                'ordering': ['application', 'trl__level'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgePartnerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_allotted', models.DateField(blank=True, null=True)),
                ('date_connected', models.DateField(blank=True, null=True)),
                ('support_requested', models.TextField(blank=True)),
                ('support_to_be_provided', models.TextField(blank=True)),
                ('support_provided', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Support Requested'), ('connected', 'Knowledge Partner Connected'), ('in_progress', 'Support In Progress'), ('completed', 'Support Completed')], default='requested', max_length=15)),
                ('advisory_remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.knowledgepartner')),
                ('trl_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_assignments', to='core.applicationtrlstage')),
            ],
            options={
                'ordering': ['-date_allotted'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('query_text', models.TextField(blank=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('response', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.knowledgepartnerassignment')),
            ],
            options={
                'ordering': ['assignment', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PartnerMilestoneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_templates', to='core.knowledgepartner')),
            ],
            options={
                'ordering': ['partner', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('action_taken', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=15)),
                ('date_achieved', models.DateField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.knowledgepartnerassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.partnermilestonetemplate')),
            ],
            options={
                'ordering': ['assignment', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TACMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_ref_no', models.CharField(blank=True, max_length=50)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('first_response_date', models.DateField(blank=True, null=True)),
                ('first_meeting_outcome', models.TextField(blank=True)),
                ('response_emailed_date', models.DateField(blank=True, null=True)),
                ('final_tac_response', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tac_meetings', to='core.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='TRLProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_on', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trl_history', to='core.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.trldefinition')),
            ],
            options={
                'ordering': ['application', 'changed_on'],
            },
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['email'], name='core_applic_email_0c11e5_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['name'], name='core_applic_name_203b51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='followup',
            unique_together={('assignment', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='partnermilestonetemplate',
            unique_together={('partner', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='applicationtrlstage',
            unique_together={('application', 'trl')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='core_applic_status_148db8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['medtech_type'], name='core_applic_medtech_81bf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['risk_classification'], name='core_applic_risk_cl_6813b1_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['date_received'], name='core_applic_date_re_bcce3b_idx'),
        ),
    ]
