# Generated by Django 6.1 on 2026-09-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='medtech_type',
            field=models.CharField(choices=[('MM-DD', 'MM-DD'), ('MM-VT', 'MM-VT'), ('MM-AT', 'MM-AT'), ('MM-IVD', 'MM-IVD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('closed', 'Completed'), ('resolved', 'Resolved'), ('assigned_to_kp', 'Assigned to Knowledge Partner')], db_index=True, default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerassignment',
            name='status',
            field=models.CharField(choices=[('requested', 'Support Requested'), ('connected', 'Partner Connected'), ('in_progress', 'Support In Progress'), ('completed', 'Support Completed')], default='requested', max_length=15),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Completed')], default='open', max_length=15),
        ),
    ]
