# Generated by Django 6.1 on 2026-09-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_application_medtech_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trldefinition',
            options={'ordering': ['medtech_type', 'level']},
        ),
        migrations.AddField(
            model_name='trldefinition',
            name='medtech_type',
            field=models.CharField(blank=True, choices=[('MM-DD', 'Device & Diagnostics'), ('MM-VT', 'Vaccines & Therapeutics'), ('MM-AT', 'Assitive Technologies')], help_text='Leave blank if this TRL definition applies to all MedTech types.', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='medtech_type',
            field=models.CharField(choices=[('MM-DD', 'Device & Diagnostics'), ('MM-VT', 'Vaccines & Therapeutics'), ('MM-AT', 'Assitive Technologies')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('closed', 'Completed'), ('resolved', 'Resolved'), ('assigned_to_kp', 'Assigned to KP')], db_index=True, default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerassignment',
            name='status',
            field=models.CharField(choices=[('connected', 'Partner Connected'), ('completed', 'Support Completed')], default='connected', max_length=15),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('closed', 'Completed'), ('notyeststart', 'Not Yet Started')], default='in_progress', max_length=15),
        ),
        migrations.AlterField(
            model_name='trldefinition',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='trldefinition',
            unique_together={('level', 'medtech_type')},
        ),
    ]
