# Generated by Django 6.1 on 2026-09-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_application_created_by'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='core_applic_status_148db8_idx',
        ),
        migrations.AlterField(
            model_name='application',
            name='reference_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
