# Generated by Django 6.1 on 2026-09-21 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_knowledgepartner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trldefinition',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='trldefinition',
            name='medtech_type',
            field=models.CharField(choices=[('MM-DD', 'Device & Diagnostics'), ('MM-VT', 'Vaccines & Therapeutics'), ('MM-AT', 'Assitive Technologies')], help_text='Leave blank if this TRL definition applies to all MedTech types.', max_length=10),
        ),
    ]
