# Generated by Django 6.1 on 2026-09-23 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_trldefinition_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_changed', models.CharField(choices=[('milestone_status', 'Milestone Status'), ('remarks', 'Advisory Remarks')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.knowledgepartnerassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, help_text='Set only when field_changed is Milestone Status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='core.milestone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
