# Generated by Django 6.1 on 2026-09-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_assignmentchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentchangelog',
            name='field_changed',
            field=models.CharField(choices=[('milestone_status', 'Milestone Status'), ('remarks', 'Remarks')], max_length=20),
        ),
    ]
