# Generated by Django 6.1 on 2026-09-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_assignmentchangelog_field_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
