# Generated by Django 6.1 on 2026-09-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_milestone_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentchangelog',
            name='field_changed',
            field=models.CharField(choices=[('milestone_status', 'Milestone Status'), ('remarks', 'Remarks'), ('milestone_remarks', 'Milestone Remarks')], max_length=20),
        ),
    ]
