# Generated by Django 6.1 on 2026-09-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_assignmentchangelog_field_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reason_for_closure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
