# Generated by Django 6.1 on 2026-09-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_application_reason_for_closure'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='summary_Technology',
            field=models.TextField(blank=True, null=True),
        ),
    ]
