# Generated by Django 6.1 on 2026-09-28 11:51

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_application_summary_technology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('closed', 'Closed'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgepartnerassignment',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('completed', 'Support Completed')], default='connected', max_length=15),
        ),
        migrations.CreateModel(
            name='TRLStageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, upload_to=core.models.trl_attachment_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'zip'])])),
                ('original_name', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('uploader_role', models.CharField(choices=[('admin', 'Admin'), ('partner', 'Knowledge Partner'), ('innovator', 'Innovator')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trl_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.applicationtrlstage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
