# Generated by Django 6.1 on 2026-10-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='allocated_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='closure_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='current_technology_stage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_interaction',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='financial_opportunities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='informed_can_come_back',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interaction_status_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='kind_of_support_required',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='kp_assigned',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='kp_assigned_handholding',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='kp_assigned_screening',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='need_to_call',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='requires_support',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sorting_remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='still_working_on_technology',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='support_given',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tac_closed_in',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='test_license_copy_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='test_license_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='tl_facilitated',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
