# Generated by Django 6.1 on 2026-09-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0006_remove_application_core_applic_status_148db8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applicant',
            field=models.OneToOneField(blank=True, help_text='Only set for users with role=Innovator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='core.applicant'),
        ),
    ]
